import {
  hpLaptop,
  iphone13,
  boatHeadphones,
  samsungWatch,
  dellInspiron,
  lenovoSlim,
  s21fe,
  oneplusNord,
  sonyHeadphones,
  jblSpeaker,
  airpodsPro,
  canonCamera,
  miBand,
  asusTuf,
} from "./Images/images";

const PRODUCTS = [
  
  {
    id: 1,
    name: "HP Pavilion 15 Laptop",
    brand: "HP",
    category: "laptop",
    price: 58999,
    originalPrice: 65999,
    discount: 11,
    rating: 4.4,
    reviewsCount: 1245,
    images: [hpLaptop],
    description:
      "HP Pavilion 15 with 11th Gen Intel Core i5 processor, 16GB RAM and 512GB SSD delivers powerful performance for work and entertainment.",
    highlights: [
      "Intel Core i5 11th Gen",
      "16 GB DDR4 RAM",
      "512 GB SSD",
      "15.6 inch Full HD Display",
      "Windows 11 Home",
    ],
  },

  {
    id: 2,
    name: "Apple iPhone 13",
    brand: "Apple",
    category: "mobile",
    price: 62999,
    originalPrice: 69999,
    discount: 10,
    rating: 4.6,
    reviewsCount: 9850,
    images: [iphone13],
    description:
      "iPhone 13 features a powerful A15 Bionic chip, advanced dual-camera system, and Super Retina XDR display.",
    highlights: [
      "128 GB ROM",
      "6.1 inch Super Retina XDR Display",
      "A15 Bionic Chip",
      "12MP Dual Camera",
      "iOS 17 Supported",
    ],
  },

  {
    id: 3,
    name: "Boat Rockerz 450 Headphones",
    brand: "boAt",
    category: "headphone",
    price: 1999,
    originalPrice: 3999,
    discount: 50,
    rating: 4.1,
    reviewsCount: 22130,
    images: [boatHeadphones],
    description:
      "boAt Rockerz 450 wireless headphones with powerful bass, 40mm drivers, and up to 15 hours of playback.",
    highlights: [
      "Wireless Bluetooth Headphones",
      "40mm Drivers",
      "15 Hours Playback",
      "Lightweight Design",
    ],
  },

  {
    id: 4,
    name: "Samsung Galaxy Watch 4",
    brand: "Samsung",
    category: "watch",
    price: 11999,
    originalPrice: 15999,
    discount: 25,
    rating: 4.3,
    reviewsCount: 4320,
    images: [samsungWatch],
    description:
      "Samsung Galaxy Watch 4 tracks your health with ECG, blood oxygen monitoring, and fitness tracking.",
    highlights: [
      "AMOLED Display",
      "Health & Fitness Tracking",
      "ECG & SpO2",
      "Water Resistant",
    ],
  },

  {
    id: 5,
    name: "Dell Inspiron 14 Laptop",
    brand: "Dell",
    category: "laptop",
    price: 54999,
    originalPrice: 61999,
    discount: 11,
    rating: 4.2,
    reviewsCount: 980,
    images: [dellInspiron],
    description:
      "Dell Inspiron 14 powered by Intel Core i5 processor with fast SSD storage for smooth multitasking.",
    highlights: [
      "Intel Core i5 11th Gen",
      "8 GB RAM",
      "512 GB SSD",
      "14 inch Full HD Display",
      "Windows 11",
    ],
  },

  {
    id: 6,
    name: "Lenovo IdeaPad Slim 3",
    brand: "Lenovo",
    category: "laptop",
    price: 46999,
    originalPrice: 53999,
    discount: 13,
    rating: 4.1,
    reviewsCount: 2150,
    images: [lenovoSlim],
    description:
      "Lenovo IdeaPad Slim 3 with Ryzen 5 processor delivers solid everyday performance.",
    highlights: [
      "AMD Ryzen 5",
      "8 GB RAM",
      "512 GB SSD",
      "15.6 inch Display",
      "Windows 11",
    ],
  },

  {
    id: 7,
    name: "Samsung Galaxy S21 FE",
    brand: "Samsung",
    category: "mobile",
    price: 36999,
    originalPrice: 49999,
    discount: 26,
    rating: 4.4,
    reviewsCount: 7680,
    images: [s21fe],
    description:
      "Samsung Galaxy S21 FE with powerful processor, smooth AMOLED display and pro-grade camera.",
    highlights: [
      "8 GB RAM",
      "128 GB Storage",
      "6.4 inch AMOLED Display",
      "64MP Camera",
      "5G Ready",
    ],
  },

  {
    id: 8,
    name: "OnePlus Nord CE 3 Lite",
    brand: "OnePlus",
    category: "mobile",
    price: 19999,
    originalPrice: 24999,
    discount: 20,
    rating: 4.3,
    reviewsCount: 5400,
    images: [oneplusNord],
    description:
      "OnePlus Nord CE 3 Lite offers a smooth 120Hz display with fast charging support.",
    highlights: [
      "6.72 inch 120Hz Display",
      "108MP Camera",
      "5000mAh Battery",
      "5G Support",
    ],
  },

  {
    id: 9,
    name: "Sony WH-1000XM4 Headphones",
    brand: "Sony",
    category: "headphone",
    price: 22999,
    originalPrice: 29999,
    discount: 23,
    rating: 4.7,
    reviewsCount: 18500,
    images: [sonyHeadphones],
    description:
      "Industry-leading noise cancellation with premium sound quality and comfort.",
    highlights: [
      "Active Noise Cancellation",
      "30 Hours Battery",
      "Bluetooth 5.0",
      "Touch Controls",
    ],
  },

  {
    id: 10,
    name: "JBL Flip 6 Bluetooth Speaker",
    brand: "JBL",
    category: "speaker",
    price: 9999,
    originalPrice: 13999,
    discount: 29,
    rating: 4.5,
    reviewsCount: 6100,
    images: [jblSpeaker],
    description:
      "Portable Bluetooth speaker with powerful bass and waterproof design.",
    highlights: [
      "Waterproof",
      "12 Hours Playback",
      "Deep Bass",
      "Portable Design",
    ],
  },

  {
    id: 11,
    name: "Apple AirPods Pro (2nd Gen)",
    brand: "Apple",
    category: "accessory",
    price: 23999,
    originalPrice: 26999,
    discount: 11,
    rating: 4.6,
    reviewsCount: 12400,
    images: [airpodsPro],
    description:
      "AirPods Pro with active noise cancellation and immersive spatial audio.",
    highlights: [
      "Active Noise Cancellation",
      "Spatial Audio",
      "MagSafe Charging",
      "Sweat Resistant",
    ],
  },

  {
    id: 12,
    name: "Canon EOS 1500D DSLR Camera",
    brand: "Canon",
    category: "camera",
    price: 33999,
    originalPrice: 38999,
    discount: 13,
    rating: 4.4,
    reviewsCount: 7200,
    images: [canonCamera],
    description:
      "Canon EOS 1500D DSLR with 24.1MP sensor for stunning photography.",
    highlights: [
      "24.1 MP Camera",
      "Wi-Fi Support",
      "Full HD Video",
      "APS-C Sensor",
    ],
  },

  {
    id: 13,
    name: "Mi Smart Band 6",
    brand: "Xiaomi",
    category: "watch",
    price: 2999,
    originalPrice: 3999,
    discount: 25,
    rating: 4.2,
    reviewsCount: 18200,
    images: [miBand],
    description:
      "Fitness band with AMOLED display and advanced health tracking.",
    highlights: [
      "AMOLED Display",
      "Heart Rate Monitor",
      "SpO2 Tracking",
      "14-Day Battery",
    ],
  },

  {
    id: 14,
    name: "Asus TUF Gaming F15",
    brand: "Asus",
    category: "laptop",
    price: 74999,
    originalPrice: 84999,
    discount: 12,
    rating: 4.5,
    reviewsCount: 3100,
    images: [asusTuf],
    description:
      "Asus TUF Gaming F15 with powerful graphics and high refresh rate display.",
    highlights: [
      "Intel Core i7",
      "RTX 3050 GPU",
      "144Hz Display",
      "16 GB RAM",
    ],
  },
    {
    id: 15,
    name: "HP Victus Gaming Laptop",
    brand: "HP",
    category: "laptop",
    price: 82999,
    originalPrice: 92999,
    discount: 11,
    rating: 4.5,
    reviewsCount: 4200,
    images: [hpLaptop],
    description: "HP Victus gaming laptop with powerful performance and thermal efficiency.",
    highlights: ["Intel Core i7", "16 GB RAM", "RTX Graphics", "144Hz Display"],
  },

  {
    id: 16,
    name: "Dell XPS 13",
    brand: "Dell",
    category: "laptop",
    price: 99999,
    originalPrice: 112999,
    discount: 12,
    rating: 4.6,
    reviewsCount: 3100,
    images: [dellInspiron],
    description: "Premium ultrabook with stunning display and lightweight design.",
    highlights: ["Intel Core i7", "16 GB RAM", "512 GB SSD", "13.4 inch Display"],
  },

  {
    id: 17,
    name: "Lenovo Legion 5",
    brand: "Lenovo",
    category: "laptop",
    price: 88999,
    originalPrice: 99999,
    discount: 11,
    rating: 4.7,
    reviewsCount: 5200,
    images: [lenovoSlim],
    description: "High-performance gaming laptop with Ryzen processor.",
    highlights: ["AMD Ryzen 7", "RTX GPU", "16 GB RAM", "165Hz Display"],
  },

  {
    id: 18,
    name: "iPhone 14",
    brand: "Apple",
    category: "mobile",
    price: 69999,
    originalPrice: 79999,
    discount: 12,
    rating: 4.7,
    reviewsCount: 11500,
    images: [iphone13],
    description: "iPhone 14 with improved camera and battery life.",
    highlights: ["A15 Bionic", "OLED Display", "12MP Camera", "iOS"],
  },

  {
    id: 19,
    name: "Samsung Galaxy S23",
    brand: "Samsung",
    category: "mobile",
    price: 74999,
    originalPrice: 84999,
    discount: 12,
    rating: 4.6,
    reviewsCount: 8700,
    images: [s21fe],
    description: "Flagship Samsung phone with premium camera performance.",
    highlights: ["Snapdragon Processor", "AMOLED Display", "50MP Camera"],
  },

  {
    id: 20,
    name: "OnePlus 11R",
    brand: "OnePlus",
    category: "mobile",
    price: 39999,
    originalPrice: 44999,
    discount: 11,
    rating: 4.4,
    reviewsCount: 6400,
    images: [oneplusNord],
    description: "Fast and smooth OnePlus smartphone with AMOLED display.",
    highlights: ["120Hz Display", "Snapdragon CPU", "Fast Charging"],
  },

  {
    id: 21,
    name: "boAt Airdopes 141",
    brand: "boAt",
    category: "accessory",
    price: 1299,
    originalPrice: 2999,
    discount: 57,
    rating: 4.2,
    reviewsCount: 35000,
    images: [boatHeadphones],
    description: "True wireless earbuds with long battery life.",
    highlights: ["42H Playback", "Fast Charge", "Bluetooth 5.1"],
  },

  {
    id: 22,
    name: "Sony WF-1000XM4",
    brand: "Sony",
    category: "accessory",
    price: 18999,
    originalPrice: 22999,
    discount: 17,
    rating: 4.6,
    reviewsCount: 9200,
    images: [sonyHeadphones],
    description: "Premium noise-cancelling earbuds from Sony.",
    highlights: ["ANC", "Wireless Charging", "Hi-Res Audio"],
  },

  {
    id: 23,
    name: "JBL Tune 760NC",
    brand: "JBL",
    category: "headphone",
    price: 7999,
    originalPrice: 10999,
    discount: 27,
    rating: 4.3,
    reviewsCount: 8100,
    images: [jblSpeaker],
    description: "Wireless headphones with active noise cancellation.",
    highlights: ["ANC", "35H Battery", "Dual Pairing"],
  },

  {
    id: 24,
    name: "Samsung Galaxy Buds 2",
    brand: "Samsung",
    category: "accessory",
    price: 8999,
    originalPrice: 11999,
    discount: 25,
    rating: 4.4,
    reviewsCount: 7600,
    images: [airpodsPro],
    description: "Compact earbuds with immersive sound.",
    highlights: ["ANC", "Lightweight", "Wireless Charging"],
  },

  {
    id: 25,
    name: "Apple Watch SE",
    brand: "Apple",
    category: "watch",
    price: 29999,
    originalPrice: 33999,
    discount: 12,
    rating: 4.6,
    reviewsCount: 6800,
    images: [samsungWatch],
    description: "Smartwatch with fitness and health tracking.",
    highlights: ["Heart Rate", "Sleep Tracking", "GPS"],
  },

  {
    id: 26,
    name: "Noise ColorFit Pro 4",
    brand: "Noise",
    category: "watch",
    price: 3499,
    originalPrice: 5999,
    discount: 42,
    rating: 4.3,
    reviewsCount: 24000,
    images: [miBand],
    description: "Affordable smartwatch with AMOLED display.",
    highlights: ["AMOLED", "SpO2", "100+ Watch Faces"],
  },

  {
    id: 27,
    name: "Fire-Boltt Phoenix",
    brand: "Fire-Boltt",
    category: "watch",
    price: 1999,
    originalPrice: 3999,
    discount: 50,
    rating: 4.1,
    reviewsCount: 19500,
    images: [miBand],
    description: "Bluetooth calling smartwatch.",
    highlights: ["Calling", "SpO2", "Metal Body"],
  },

  {
    id: 28,
    name: "Canon EOS 200D II",
    brand: "Canon",
    category: "camera",
    price: 48999,
    originalPrice: 54999,
    discount: 11,
    rating: 4.5,
    reviewsCount: 4300,
    images: [canonCamera],
    description: "Compact DSLR with dual pixel autofocus.",
    highlights: ["24.1MP", "4K Video", "Wi-Fi"],
  },

  {
    id: 29,
    name: "Sony Alpha a6400",
    brand: "Sony",
    category: "camera",
    price: 68999,
    originalPrice: 74999,
    discount: 8,
    rating: 4.7,
    reviewsCount: 5200,
    images: [canonCamera],
    description: "Mirrorless camera with fast autofocus.",
    highlights: ["24.2MP", "4K Video", "Real-Time AF"],
  },

  {
    id: 30,
    name: "JBL Go 3",
    brand: "JBL",
    category: "speaker",
    price: 2999,
    originalPrice: 4999,
    discount: 40,
    rating: 4.4,
    reviewsCount: 18000,
    images: [jblSpeaker],
    description: "Ultra-portable Bluetooth speaker.",
    highlights: ["Waterproof", "Punchy Bass", "Portable"],
  },

  {
    id: 31,
    name: "Sony SRS-XB13",
    brand: "Sony",
    category: "speaker",
    price: 3999,
    originalPrice: 5999,
    discount: 33,
    rating: 4.5,
    reviewsCount: 12500,
    images: [sonyHeadphones],
    description: "Compact speaker with extra bass.",
    highlights: ["Extra Bass", "16H Battery", "IP67"],
  },

  {
    id: 32,
    name: "Asus ROG Zephyrus G14",
    brand: "Asus",
    category: "laptop",
    price: 119999,
    originalPrice: 134999,
    discount: 11,
    rating: 4.8,
    reviewsCount: 3900,
    images: [asusTuf],
    description: "Powerful gaming laptop in compact size.",
    highlights: ["Ryzen 9", "RTX GPU", "QHD Display"],
  },

  {
    id: 33,
    name: "Redmi Note 13 Pro",
    brand: "Xiaomi",
    category: "mobile",
    price: 25999,
    originalPrice: 29999,
    discount: 13,
    rating: 4.4,
    reviewsCount: 9100,
    images: [iphone13],
    description: "Camera-centric smartphone with AMOLED display.",
    highlights: ["200MP Camera", "120Hz Display", "Fast Charge"],
  },

  {
    id: 34,
    name: "Realme Narzo 60",
    brand: "Realme",
    category: "mobile",
    price: 17999,
    originalPrice: 21999,
    discount: 18,
    rating: 4.2,
    reviewsCount: 8300,
    images: [oneplusNord],
    description: "Budget-friendly 5G smartphone.",
    highlights: ["5G", "AMOLED", "5000mAh"],
  },

  {
    id: 35,
    name: "Apple Magic Mouse",
    brand: "Apple",
    category: "accessory",
    price: 7499,
    originalPrice: 8999,
    discount: 17,
    rating: 4.3,
    reviewsCount: 4100,
    images: [airpodsPro],
    description: "Wireless mouse with multi-touch surface.",
    highlights: ["Multi-Touch", "Rechargeable", "Mac Compatible"],
  },

  {
    id: 36,
    name: "Logitech MX Master 3S",
    brand: "Logitech",
    category: "accessory",
    price: 9999,
    originalPrice: 12999,
    discount: 23,
    rating: 4.7,
    reviewsCount: 6200,
    images: [airpodsPro],
    description: "Advanced wireless mouse for productivity.",
    highlights: ["Ergonomic", "USB-C", "Multi-Device"],
  },

  {
    id: 37,
    name: "HP Wireless Keyboard & Mouse",
    brand: "HP",
    category: "accessory",
    price: 2499,
    originalPrice: 3999,
    discount: 38,
    rating: 4.2,
    reviewsCount: 8900,
    images: [hpLaptop],
    description: "Comfortable keyboard and mouse combo.",
    highlights: ["Wireless", "Long Battery", "Compact Design"],
  },

  {
    id: 38,
    name: "Samsung 27-inch Curved Monitor",
    brand: "Samsung",
    category: "accessory",
    price: 18999,
    originalPrice: 23999,
    discount: 21,
    rating: 4.5,
    reviewsCount: 5400,
    images: [dellInspiron],
    description: "Immersive curved monitor for work and gaming.",
    highlights: ["27 inch", "75Hz", "Full HD"],
  },

  {
    id: 39,
    name: "LG UltraWide Monitor",
    brand: "LG",
    category: "accessory",
    price: 24999,
    originalPrice: 29999,
    discount: 17,
    rating: 4.6,
    reviewsCount: 3600,
    images: [dellInspiron],
    description: "UltraWide display for productivity.",
    highlights: ["21:9 Ratio", "IPS Panel", "HDR10"],
  },

  {
    id: 40,
    name: "Canon PIXMA Printer",
    brand: "Canon",
    category: "accessory",
    price: 5499,
    originalPrice: 7999,
    discount: 31,
    rating: 4.2,
    reviewsCount: 11200,
    images: [canonCamera],
    description: "All-in-one inkjet printer for home use.",
    highlights: ["Print Scan Copy", "Wi-Fi", "Compact"],
  },

  {
    id: 41,
    name: "TP-Link WiFi Router",
    brand: "TP-Link",
    category: "accessory",
    price: 2999,
    originalPrice: 4999,
    discount: 40,
    rating: 4.4,
    reviewsCount: 15000,
    images: [asusTuf],
    description: "High-speed WiFi router for home.",
    highlights: ["Dual Band", "High Speed", "Wide Coverage"],
  },

  {
    id: 42,
    name: "Seagate 1TB External HDD",
    brand: "Seagate",
    category: "accessory",
    price: 3999,
    originalPrice: 5999,
    discount: 33,
    rating: 4.5,
    reviewsCount: 21000,
    images: [hpLaptop],
    description: "Portable external hard drive.",
    highlights: ["1TB Storage", "USB 3.0", "Portable"],
  },

  {
    id: 43,
    name: "Sandisk 128GB Pendrive",
    brand: "SanDisk",
    category: "accessory",
    price: 999,
    originalPrice: 1799,
    discount: 44,
    rating: 4.4,
    reviewsCount: 27000,
    images: [hpLaptop],
    description: "High-speed USB 3.0 pendrive.",
    highlights: ["128GB", "USB 3.0", "Compact"],
  },

  {
    id: 44,
    name: "Mi Power Bank 20000mAh",
    brand: "Xiaomi",
    category: "accessory",
    price: 2199,
    originalPrice: 2999,
    discount: 27,
    rating: 4.5,
    reviewsCount: 34000,
    images: [miBand],
    description: "High-capacity fast charging power bank.",
    highlights: ["20000mAh", "Fast Charging", "Dual Output"],
  },
];


export default PRODUCTS;